version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:13.7.0
      - image: circleci/mongo:4.2.3
        environment:
          - MONGO_INITDB_DATABASE: test
      - image: roamgg/snowflake:latest
        
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
      - run:
          name: install dependencies
          command: yarn install
      - save_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
      - run:
          name: test
          command: yarn run test
      - store_artifacts:
          path: coverage/clover.xml
          prefix: coverage
      - run:
          name: upload coverage report
          command: bash <(curl -s https://codecov.io/bash)